version: 2
jobs:
  build:
    docker:
      - image: sravanik/icc-demo-docker:0.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    steps:
      - checkout

      - run:
          name: Build and Test Project
          command: source /opt/intel/bin/iccvars.sh -arch intel64 &&
                   printenv IS_LICENSE_DATA_LINUX | openssl base64 -d -A > /opt/intel/licenses/license.lic && 
                   icc -v && 
                   mkdir build && cd build && 
                   FC=ifort CC=icc CXX=icpc cmake ../src && 
                   make && 
                   make test
